FROM ubuntu:latest
RUN apt update -y
RUN apt install -y \
    libglib2.0-dev \
    libgtk2.0-dev \
    libvte-dev \
    autotools-dev \
    intltool \
    xsltproc \
    libxml2-utils \
    docbook-xml \
    docbook-xsl
